speedtest:
  image: ghcr.io/akvorrat/netzbremse-measurement:latest
  variables:
    NB_SPEEDTEST_ACCEPT_POLICY: "true"
    NB_SPEEDTEST_JSON_OUT_DIR: "./json-results"
  artifacts:
    paths:
      - json-results/
    expire_in: 30 days
  script:
    - echo "Running speedtest..."
