netzbremse-measurement:
  image: ghcr.io/akvorrat/netzbremse-measurement:latest
  variables:
    NB_SPEEDTEST_ACCEPT_POLICY: "true"
    NB_SPEEDTEST_INTERVAL: 0
    NB_SPEEDTEST_TIMEOUT: "3600"
    NB_SPEEDTEST_RETRY_INTERVAL: 900
    NB_SPEEDTEST_RETRY_COUNT: "3"
    NB_SPEEDTEST_URL: https://netzbremse.de/speed
    NB_SPEEDTEST_BROWSER_DATA_DIR: ./tmp-browser-data
    NB_SPEEDTEST_JSON_OUT_DIR: "$CI_PROJECT_DIR/json-results"
  artifacts:
    paths:
      - json-results/
    expire_in: 30 days
